version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stock_reactive
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: spring_app
    depends_on:
      - db
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://db:5432/stock_reactive
      SPRING_R2DBC_USERNAME: username
      SPRING_R2DBC_PASSWORD: password
      SPRING_FLYWAY_URL: jdbc:postgresql://db:5432/stock_reactive
      SPRING_FLYWAY_USER: username
      SPRING_FLYWAY_PASSWORD: password
    ports:
      - "8080:8080"

volumes:
  postgres_data:
